# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5d5b0edda37545939908fd647d10a9ae1c708a386c363517fbab24039ae1ae5eaa204581c7f6da938df5d89c741d4964506fb3992193bddf0c286097069501

test:
  secret_key_base: 3e613afd4b03ebe1a9367b162aea5e5b5af85042b0095740169ba734d991c4db9b4cb1bf2dff4e924b6a551069cbada2cd05cf4b2bee3bef3454d3977f4c7da6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
